# Generated by Django 4.1 on 2022-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('commercial', 'Коммерческая'), ('blog', 'Блог')], default='news', max_length=255, verbose_name='Тип/Вид'),
        ),
    ]
