# Generated by Django 4.1 on 2022-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('commercial', 'Коммерческая'), ('blog', 'Блог')], default='commercial', max_length=255, verbose_name='Тип/Вид'),
        ),
    ]
