# Generated by Django 4.1 on 2022-09-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_text_alter_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NAME'),
        ),
    ]
